import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "~/components/ui/table"

export function TimetableTable() {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>{""}</TableHead>
          <TableHead>{"月"}</TableHead>
          <TableHead>{"火"}</TableHead>
          <TableHead>{"水"}</TableHead>
          <TableHead>{"木"}</TableHead>
          <TableHead>{"金"}</TableHead>
          <TableHead>{"土"}</TableHead>
          <TableHead>{"日"}</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow>
          <TableCell>{"1"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
        </TableRow>
        <TableRow>
          <TableCell>{"2"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
        </TableRow>
        <TableRow>
          <TableCell>{"3"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
        </TableRow>
        <TableRow>
          <TableCell>{"4"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
        </TableRow>
        <TableRow>
          <TableCell>{"5"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
        </TableRow>
        <TableRow>
          <TableCell>{"6"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
        </TableRow>
        <TableRow>
          <TableCell>{"7"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
          <TableCell>{"invoice"}</TableCell>
        </TableRow>
      </TableBody>
    </Table>
  )
}
